version: "3.8"
services:
  hapi-fhir:
    build: .
    container_name: hapi-fhir
    restart: on-failure
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres-db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres-db:/var/lib/postgresql/data

  
  #static-server:
    #image: python:3.9-slim
    #container_name: static-server
    #command: python -m http.server 8000
    #restart: always
    #ports:
      #- '8000:8000'
    #volumes:
      #add the directory of the datafile here (type http://localhost:8000/app/data/ in browser to acess)
      #- directory of file (\app\data):/app/data

volumes:
  hapi-fhir-postgres-db: